import Layout from "@/components/Layout";
import Head from "next/head";
import Image from "next/image";
import profilePic from "../../public/images/profile/developer-pic-1.png";
import AnimatedText from "@/components/AnimatedText";
import Link from "next/link";
import { LinkArrow } from "@/components/Icons";
import HireMe from "@/components/HireMe";
import lightBuld from "../../public/images/svgs/miscellaneous_icons_1.svg";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <main className="flex items-center text-dark w-full min-h-screen dark:text-light">
        <Layout className="pt-0">
          <div className="flex items-center justify-between w-full">
            <div className="w-1/2">
              <div className="rounded-full overflow-hidden bg-slate-600 mx-16">
                <Image
                  src={profilePic}
                  alt="MarioDias"
                  className="w-full h-auto"
                  priority={true}
                  sizes="(max-width: 768px) 100vw, (max-width: 1200px) 50vw, 50vw"
                />
              </div>
            </div>
            <div className="w-1/2 flex flex-col items-center self-center">
              <AnimatedText
                text="Transformando visão em realidade com código e design."
                className="!text-6xl !text-left"
              />
              <p className="my-4 text-base font-medium">
                Olá,
                <br /> <br />
                Sou um Desenvolvedor Full Stack com habilidades em Design UX.
                Bem-vindo ao meu portfólio!
                <br /> <br />
                Aqui, você encontrará uma experiência envolvente e visualmente
                atraente para explorar meu trabalho e habilidades.
                <br /> <br />
                Sinta-se à vontade para explorar meus projetos. Estou ansioso
                para receber seu feedback e discutir oportunidades de
                colaboração.
                <br /> <br />
                Obrigado por visitar!
                <br />
                Mário Dias
              </p>
              <div className="flex items-center self-start mt-2">
                <Link
                  href="/cv.pdf"
                  target={"_blank"}
                  className="flex items-center bg-dark text-light p-2.5 px-6 rounded-lg text-lg font-semibold hover:bg-light 
                  hover:text-dark border-2 border-solid border-transparent hover:border-dark dark:bg-light dark:text-dark
                  dark:hover:bg-dark dark:hover:text-light dark:hover:border-light"
                  download={true}
                >
                  Currículo
                  <LinkArrow className={"w-6 ml-1"} />
                </Link>
                <Link
                  href="mailto:mspdias1@gmail.com"
                  target={"_blank"}
                  className="ml-4 text-lg font-medium capitalize text-dark underline dark:text-light"
                >
                  Contato
                </Link>
              </div>
            </div>
          </div>
        </Layout>
        <HireMe />
        <div className="absolute right-8 bottom-8 inline-block w-24">
          <Image src={lightBuld} alt="Mário Dias" className="w-full h-auto" />
        </div>
      </main>
    </>
  );
}
